__title__ = "pyecs"
__description__ = "A simple implementation of the Entity-Component pattern."
__url__ = "https://github.com/tim-fi/pyecs"
__version__ = "0.10"
__build__ = 0x00000A
__author__ = "Tim Fischer"
__author_email__ = "me@timfi.dev"
__license__ = "MIT"
__copyright__ = "Copyright 2020 Tim Fischer"
