__title__ = "pyecs"
__description__ = "An implementation of the Entity-Component-System pattern."
__url__ = "https://github.com/tim-fi/pyecs"
__version__ = "0.3"
__build__ = 0x000003
__author__ = "Tim Fischer"
__author_email__ = "tim.fischer98@hotmail.com"
__license__ = "MIT"
__copyright__ = "Copyright 2019 Tim Fischer"
