__title__ = "pyecs"
__description__ = "An implementation of the Entity-Component-System pattern."
__url__ = "https://github.com/tim-fi/pyecs"
__version__ = "0.6"
__build__ = 0x000006
__author__ = "Tim Fischer"
__author_email__ = "me@timfi.dev"
__license__ = "MIT"
__copyright__ = "Copyright 2020 Tim Fischer"
